name: Build and Publish Centralisation
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version-file: .python-version

      - name: Cache uv folder
        id: cache-uv
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-uv-${{ hashFiles('pyproject.toml') }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.9.27/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Build static files
        run: uv run python ./build.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
