name: Test Centralisation

on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]

# By default pull requests made by Dependabot have a GITHUB_TOKEN with read only permissions
# To be able to send comments `create-or-update-comment` action needs at least a `pull-requests: write` permission
# See https://github.com/peter-evans/create-or-update-comment/issues/103
permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version-file: .python-version

      - name: Cache uv folder
        id: cache-uv
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-uv-${{ hashFiles('pyproject.toml') }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.9.27/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Test the project
        run: uv run python ./check_assets.py

      - name: Build static files
        run: uv run python ./build.py
